version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    networks:
      - default

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: node-exporter
    hostname: node-exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - '9100:9100'
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    networks:
      - default

  mongo-exporter:
    image: percona/mongodb_exporter:0.39
    container_name: mongo-exporter
    hostname: mongo-exporter
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command:
      - --mongodb.uri=mongodb://mongodb_exporter:password@host.docker.internal:27017
      - --mongodb.global-conn-pool
      - --mongodb.direct-connect
      - --compatible-mode
      - --collect-all
    ports:
      - '9216:9216'
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    networks:
      - default

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - '3030:3000'
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    networks:
      - default

  loki:
    image: grafana/loki:latest
    container_name: loki
    hostname: loki
    ports:
      - '3100:3100'
    volumes:
      - ./grafana/loki-data:/data
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      TZ: 'Europe/Moscow'
    networks:
      - default
