version: '3.8'
services:
  redis:
    image: bitnami/redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --protected-mode no
    volumes:
      - ./cache:/data
