scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets:
          [
            'node-exporter:9100',
            'mongo-exporter:9216',
            'host.docker.internal:5000',
            'host.docker.internal:5003',
          ]
