version: '3.8'

networks:
  db-network:
    name: dbNetwork
    driver: bridge

services:
  db:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=db
      - POSTGRESQL_USER=postgres
    ports:
      - '5432:5432'
    restart: always
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - '15432:80'
    restart: always
    networks:
      - db-network
    depends_on:
      - db
